version: '2'

services:
  redis:
    image: redis:alpine
    container_name: redis-store
    ports:
      - 6379:6379

  datastore:
    image: mongo
    container_name: mongo-store
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=${root}
      - MONGO_INITDB_ROOT_PASSWORD=${pass}
    volumes:
      - /home/sudipto/.myDB/sweetgin/db:/data/db
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null